services:
    _defaults:
        public: true

    bitbag_sylius_mollie_plugin.action.capture:
        class: BitBag\SyliusMolliePlugin\Action\CaptureAction
        tags:
            - { name: payum.action, factory: mollie, alias: payum.action.capture }
            - { name: payum.action, factory: mollie_subscription, alias: payum.action.capture }

    bitbag_sylius_mollie_plugin.action.notify:
        class: BitBag\SyliusMolliePlugin\Action\NotifyAction
        arguments:
            - "@bitbag_sylius_mollie_plugin.get_http_request"
            - "@bitbag_sylius_mollie_plugin.repository.subscription"
        tags:
            - { name: payum.action, factory: mollie, alias: payum.action.notify }
            - { name: payum.action, factory: mollie_subscription, alias: payum.action.notify }

    bitbag_sylius_mollie_plugin.action.status:
        class: BitBag\SyliusMolliePlugin\Action\StatusAction
        tags:
            - { name: payum.action, factory: mollie, alias: payum.action.status }
            - { name: payum.action, factory: mollie_subscription, alias: payum.action.status }

    bitbag_sylius_mollie_plugin.action.convert_payment:
        class: BitBag\SyliusMolliePlugin\Action\ConvertPaymentAction
        arguments:
            - "@sylius.payment_description_provider"
        tags:
            - { name: payum.action, factory: mollie, alias: payum.action.convert_payment }
            - { name: payum.action, factory: mollie_subscription, alias: payum.action.convert_payment }

    bitbag_sylius_mollie_plugin.payum_action.refund:
        class: BitBag\SyliusMolliePlugin\Action\RefundAction
        tags:
            - { name: payum.action, factory: mollie, alias: payum.action.refund }

    bitbag_sylius_mollie_plugin.payum_action.api.create_customer:
        class: BitBag\SyliusMolliePlugin\Action\Api\CreateCustomerAction
        tags:
            - { name: payum.action, factory: mollie, alias: payum.action.api.create_customer }
            - { name: payum.action, factory: mollie_subscription, alias: payum.action.api.create_customer }

    bitbag_sylius_mollie_plugin.payum_action.api.create_sepa_mandate:
        class: BitBag\SyliusMolliePlugin\Action\Api\CreateSepaMandateAction
        arguments:
            - "@session"
        tags:
            - { name: payum.action, factory: mollie_subscription, alias: payum.action.api.create_sepa_mandate }

    bitbag_sylius_mollie_plugin.payum_action.api.create_recurring_subscription:
        class: BitBag\SyliusMolliePlugin\Action\Api\CreateRecurringSubscriptionAction
        arguments:
            - "@bitbag_sylius_mollie_plugin.factory.subscription"
            - "@bitbag_sylius_mollie_plugin.manager.subscription"
            - "@sm.factory"
            - "@sylius.repository.order"
        tags:
            - { name: payum.action, factory: mollie_subscription, alias: payum.action.api.create_recurring_subscription }

    bitbag_sylius_mollie_plugin.payum_action.api.create_recurring_payment:
        class: BitBag\SyliusMolliePlugin\Action\Api\CreateRecurringPaymentAction
        arguments:
            - "@bitbag_sylius_mollie_plugin.factory.recurring_payment"
            - "@bitbag_sylius_mollie_plugin.manager.recurring_payment"
            - "@sylius.repository.order"
            - "@bitbag_sylius_mollie_plugin.repository.recurring_payment"
        tags:
            - { name: payum.action, factory: mollie, alias: payum.action.api.create_recurring_payment }

    bitbag_sylius_mollie_plugin.payum_action.state_machine.status_recurring_subscription:
        class: BitBag\SyliusMolliePlugin\Action\StateMachine\StatusRecurringSubscriptionAction
        arguments:
            - "@bitbag_sylius_mollie_plugin.manager.subscription"
            - "@sm.factory"
        tags:
            - { name: payum.action, factory: mollie_subscription, alias: payum.action.state_machine.status_recurring_subscription }

    bitbag_sylius_mollie_plugin.payum_action.state_machine.cancel_recurring_subscription:
        class: BitBag\SyliusMolliePlugin\Action\Api\CancelRecurringSubscriptionAction
        tags:
            - { name: payum.action, factory: mollie_subscription, alias: payum.action.state_machine.cancel_recurring_subscription }
