imports:
    - { resource: "@BitBagSyliusMolliePlugin/Resources/config/services.yml" }
    - { resource: "@BitBagSyliusMolliePlugin/Resources/config/resources.yml" }
    - { resource: "@BitBagSyliusMolliePlugin/Resources/config/state_machine.yml" }

twig:
    globals:
        subscription_mollie_repository: "@bitbag_sylius_mollie_plugin.repository.subscription"
        recurring_payment_mollie_repository: "@bitbag_sylius_mollie_plugin.repository.recurring_payment"

sylius_grid:
    templates:
        action:
            cancel_subscription_mollie: "@BitBagSyliusMolliePlugin/Grid/Action/cancelSubscriptionMollie.html.twig"
    grids:
        sylius_shop_account_order:
            actions:
                item:
                    cancel_subscription_mollie:
                        type: cancel_subscription_mollie
                        label: bitbag_sylius_mollie_plugin.ui.cancel_subscription
                        options:
                            link:
                                route: bitbag_sylius_mollie_plugin_cancel_subscription_mollie
                                parameters:
                                    orderId: resource.id
