sylius_resource:
    resources:
        bitbag_sylius_mollie_plugin.recurring_payment:
            driver: doctrine/orm
            classes:
                model: BitBag\SyliusMolliePlugin\Entity\RecurringPayment
                repository: BitBag\SyliusMolliePlugin\Repository\RecurringPaymentRepository
